### ISSUE TITLE
Style changes for the download feature of csv and json

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#107]

**Comment by KosovareS** [comment]
@ferideadili when I download some results in the form of csv file, I see the results as below : 

<img width="621" alt="screen shot 2017-04-11 at 2 52 31 pm" src="https://cloud.githubusercontent.com/assets/16719237/24910257/7bfca36a-1ec7-11e7-80aa-61863364f870.png">

**Comment by ferideadili** [comment]
@dafinaolluri @KosovareSahatqija the problem is only for mac devices, since the spreedsheet does not support csv and utf8 conversion. One solution is to open it from google drive.
