### ISSUE TITLE
Convert the Cyrillic text when switching to english language

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#109]

**Comment by KosovareS** [comment]
@ferideadili when I switch the language in English and search in "Parlamentary" the indicators are duplicated as in the picture bellow: 
<img width="272" alt="screen shot 2017-04-20 at 3 49 39 pm" src="https://cloud.githubusercontent.com/assets/16719237/25234034/2b5a59c2-25e1-11e7-9394-4a3c76e2c08a.png">
