### ISSUE TITLE
Import data for the year 2016.

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#33]

**Comment by ferideadili** [comment]
Did the import, but again having problems, wrote to Ivana for the necessary changes.

**Comment by artaabdullahu** [comment]
@ferideadili I can not see those data in Web. Maybe you have imported that in code.

**Comment by ferideadili** [comment]
@artaabdullahu yes, but again not implemented here, since there are needed still some corrections.Waiting from Ivana and than you will see.
