### ISSUE TITLE
As as user I want to see the text in Cyrillic, so I can relate to the data of the elections.

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#34]

**Comment by artaabdullahu** [comment]
@dafinaolluri  Can You Please Be More Specific!

**Comment by georgeslabreche** [comment]
@artaabdullahu all text needs to be in Cyrillic. If there is any text anywhere that is not in Cyrillic then this story should not be accepted. Please provide screenshots of areas that do not have text in Cyrillic.

**Comment by artaabdullahu** [comment]
@georgeslabreche OK, I understand now. Thank you.

**Comment by artaabdullahu** [comment]
Data table should to be with text in Cyrillic, not English.
![image](https://cloud.githubusercontent.com/assets/21961919/22209425/b5c3e582-e186-11e6-8d47-b81f6d83b6ae.png)

**Comment by dafinaolluri** [comment]
@ferideadili check this issue if you haven't because we need to close Sprint 0.

**Comment by artaabdullahu** [comment]
@dafinaolluri @georgeslabreche Test estimation: 1h
