### ISSUE TITLE
As a user when I select a party list or a candidate, I want to be able to see the color in the map to be differently in each territory. 

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#36]
**Description**

When the user selects a political party or candidate the map should be filled in colours, and each colour is dependent on the territory results and the candidate. 

**Acceptance Criteria**

- [x] The colours should be from light to dark (depending on the results of the territory and candidate - the lowest percentage the lighter the colour, and Vice Versa.

**Comment by artaabdullahu** [comment]
@dafinaolluri @georgeslabreche Test estimation: 3h
