### ISSUE TITLE
As an user I want to be able to see the layout of the map same as in the Georgia Election Data site.

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#38]
**Description**

See example in the Georgia Election Data site.: https://elections.jumpstart.ge/en

**Comment by artaabdullahu** [comment]
![image](https://cloud.githubusercontent.com/assets/21961919/22424177/afb4d2c2-e6f5-11e6-8f4f-4f33f75f612d.png)


![image](https://cloud.githubusercontent.com/assets/21961919/22424306/509bff8a-e6f6-11e6-87ee-86c2ed9d97c0.png)

**Comment by artaabdullahu** [comment]
@ferideadili  Also is missing this part, see picture bellow: 
![image](https://cloud.githubusercontent.com/assets/21961919/22425848/5f9e74ac-e6fd-11e6-8aff-8bec544efcca.png)

**Comment by artaabdullahu** [comment]
@ferideadili please see the last comments that missed button for how many data do you want to see. Refer screenshot in top.

**Comment by artaabdullahu** [comment]
@ferideadili  i can not see again this button.
