### ISSUE TITLE
As a user I want to be able to have the option to switch into another language.

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#39]
**Description**

This feature can be developed in other phase or later in the project.

**Comment by KosovareS** [comment]
<img width="362" alt="screen shot 2017-04-11 at 2 53 39 pm" src="https://cloud.githubusercontent.com/assets/16719237/24910126/006ea4f0-1ec7-11e7-9e9d-82821d70c38a.png">
<img width="419" alt="screen shot 2017-04-11 at 2 54 02 pm" src="https://cloud.githubusercontent.com/assets/16719237/24910139/0a8af678-1ec7-11e7-8602-c54f4f20fda8.png">

**Comment by KosovareS** [comment]
@ferideadili even if I change the language in EN I can see the results in serbian language, as you can see in the images attached in the comments above.

**Comment by ferideadili** [comment]
@KosovareSahatqija @dafinaolluri if you mean the translation for the name of candidates or political parties, I think we don't need to translate them.
