### ISSUE TITLE
We need data to put footer.

### ISSUE THREAD

**Issue by artaabdullahu** [crtarsorg/izborna-platforma#47]

**Comment by dafinaolluri** [comment]
@ferideadili We will wait for the confirmation from Rasa when he provides information on what needs to be put in the footer.

**Comment by ferideadili** [comment]
@dafinaolluri 

Contact page?
About page?

**Comment by dafinaolluri** [comment]
@ferideadili what about contact page and about page?

**Comment by ferideadili** [comment]
@dafinaolluri we need to know if we are going to have pages or popups for these two, or are we going to include somewhere, if yes to better calculate the estimations for the next sprint.
