### ISSUE TITLE
Footer responsive.

### ISSUE THREAD

**Issue by artaabdullahu** [crtarsorg/izborna-platforma#48]
- [x] Should to improve footer in every page.

- [ ] Also must to be responsive.

<img width="523" alt="screen shot 2017-01-30 at 11 13 14 am" src="https://cloud.githubusercontent.com/assets/21961919/22419309/34833bce-e6dd-11e6-8ec0-40a127b5c5ac.png">

**Comment by artaabdullahu** [comment]
@ferideadili Now is a small problem for responsive in Firefox and in this size 289×1240 : 

![image](https://cloud.githubusercontent.com/assets/21961919/22471079/9d4a8ffa-e7d1-11e6-977d-7be99d3fca55.png)

**Comment by ferideadili** [comment]
@artaabdullahu do we phones on such width?

**Comment by artaabdullahu** [comment]
@ferideadili this size is in firefox for responsive: see
![image](https://cloud.githubusercontent.com/assets/21961919/22502453/302af076-e86d-11e6-9e71-b018e81915e8.png)
