### ISSUE TITLE
Selected page by type.

### ISSUE THREAD

**Issue by artaabdullahu** [crtarsorg/izborna-platforma#50]
![image](https://cloud.githubusercontent.com/assets/21961919/22424771/4d51c614-e6f8-11e6-9a43-0c660d9c60c1.png)

**Comment by dafinaolluri** [comment]
@artaabdullahu be more specific, the screenshot is not enough.

**Comment by artaabdullahu** [comment]
This mini bug still there. 
![image](https://cloud.githubusercontent.com/assets/21961919/22502064/ad32309a-e86b-11e6-9c9b-6ea5732a17d1.png)
