### ISSUE TITLE
Fix long text of political parties.

### ISSUE THREAD

**Issue by artaabdullahu** [crtarsorg/izborna-platforma#52]
![image](https://cloud.githubusercontent.com/assets/21961919/22460065/97bd249a-e7a3-11e6-8f4e-80109a8a966d.png)

**Comment by dafinaolluri** [comment]
**Description**

 @ferideadili Make the size of the name consistent (some of them are bigger while some others are smaller). Try to fit the long names of the political parties in the same column (colour).

**Comment by artaabdullahu** [comment]
@ferideadili The bug still yet.
![image](https://cloud.githubusercontent.com/assets/21961919/22501953/35629c9e-e86b-11e6-86fd-bed0cae5731b.png)
