### ISSUE TITLE
Индикатори part between the texts should have space.

### ISSUE THREAD

**Issue by artaabdullahu** [crtarsorg/izborna-platforma#66]
**Description**
Part of Indicators should be separated a little bit. (Qato qka i kom bo me vija horizontale te kuqe duhet mi nda pak me space sikur dy pika me poshte dukenme mire )
<img width="1274" alt="screen shot 2017-02-04 at 12 22 07 am" src="https://cloud.githubusercontent.com/assets/21961919/22612405/c1ef6e56-ea70-11e6-8f16-427d6a7a02d7.png">

**Comment by dafinaolluri** [comment]
@ferideadili
