### ISSUE TITLE
Small percentage value and piechart

### ISSUE THREAD

**Issue by ferideadili** [crtarsorg/izborna-platforma#77]
<img width="1280" alt="screen shot 2017-02-07 at 11 10 36 am" src="https://cloud.githubusercontent.com/assets/21961919/22696636/0c52b6d4-ed4f-11e6-9d1d-34a1fd065288.png">

**Comment by artaabdullahu** [comment]
The percentage value is not showing full inside piechart. (2012 - други круг[on page **8** and **15**])
Please see the screenshot bellow:
<img width="1279" alt="screen shot 2017-02-07 at 4 14 53 pm" src="https://cloud.githubusercontent.com/assets/21961919/22697297/51ccb65e-ed51-11e6-8c77-41cd57ec2266.png">
<img width="1280" alt="screen shot 2017-02-07 at 4 15 38 pm" src="https://cloud.githubusercontent.com/assets/21961919/22697296/51c986d2-ed51-11e6-8383-19b962823709.png">
